FROM postgres:14

WORKDIR /app

COPY ./pg/seed.sql /docker-entrypoint-initdb.d/seed.sql
COPY ./pg/seed.sh /docker-entrypoint-initdb.d/

RUN chmod +x /docker-entrypoint-initdb.d/seed.sh

CMD ["/docker-entrypoint-initdb.d/seed.sh"]