// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/proto/dialog/v1/dialog.proto

package dialogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    string                 `protobuf:"bytes,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_pkg_proto_dialog_v1_dialog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dialog_v1_dialog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dialog_v1_dialog_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SendMessageRequest) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_pkg_proto_dialog_v1_dialog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dialog_v1_dialog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dialog_v1_dialog_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendMessageResponse) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OtherUserId   string                 `protobuf:"bytes,2,opt,name=other_user_id,json=otherUserId,proto3" json:"other_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_pkg_proto_dialog_v1_dialog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dialog_v1_dialog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dialog_v1_dialog_proto_rawDescGZIP(), []int{2}
}

func (x *GetMessagesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetMessagesRequest) GetOtherUserId() string {
	if x != nil {
		return x.OtherUserId
	}
	return ""
}

type DialogMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    string                 `protobuf:"bytes,3,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialogMessage) Reset() {
	*x = DialogMessage{}
	mi := &file_pkg_proto_dialog_v1_dialog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogMessage) ProtoMessage() {}

func (x *DialogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dialog_v1_dialog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogMessage.ProtoReflect.Descriptor instead.
func (*DialogMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dialog_v1_dialog_proto_rawDescGZIP(), []int{3}
}

func (x *DialogMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DialogMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *DialogMessage) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *DialogMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DialogMessage) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*DialogMessage       `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_pkg_proto_dialog_v1_dialog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_dialog_v1_dialog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_dialog_v1_dialog_proto_rawDescGZIP(), []int{4}
}

func (x *GetMessagesResponse) GetMessages() []*DialogMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_pkg_proto_dialog_v1_dialog_proto protoreflect.FileDescriptor

const file_pkg_proto_dialog_v1_dialog_proto_rawDesc = "" +
	"\n" +
	" pkg/proto/dialog/v1/dialog.proto\x12\tdialog.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"f\n" +
	"\x12SendMessageRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\tR\n" +
	"receiverId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"\x83\x01\n" +
	"\x13SendMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x123\n" +
	"\asent_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\"Q\n" +
	"\x12GetMessagesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\"\n" +
	"\rother_user_id\x18\x02 \x01(\tR\votherUserId\"\xb5\x01\n" +
	"\rDialogMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x03 \x01(\tR\n" +
	"receiverId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x123\n" +
	"\asent_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\"K\n" +
	"\x13GetMessagesResponse\x124\n" +
	"\bmessages\x18\x01 \x03(\v2\x18.dialog.v1.DialogMessageR\bmessages2\xab\x01\n" +
	"\rDialogService\x12L\n" +
	"\vSendMessage\x12\x1d.dialog.v1.SendMessageRequest\x1a\x1e.dialog.v1.SendMessageResponse\x12L\n" +
	"\vGetMessages\x12\x1d.dialog.v1.GetMessagesRequest\x1a\x1e.dialog.v1.GetMessagesResponseB\x1fZ\x1dsocial/pkg/dialog/v1;dialogv1b\x06proto3"

var (
	file_pkg_proto_dialog_v1_dialog_proto_rawDescOnce sync.Once
	file_pkg_proto_dialog_v1_dialog_proto_rawDescData []byte
)

func file_pkg_proto_dialog_v1_dialog_proto_rawDescGZIP() []byte {
	file_pkg_proto_dialog_v1_dialog_proto_rawDescOnce.Do(func() {
		file_pkg_proto_dialog_v1_dialog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_dialog_v1_dialog_proto_rawDesc), len(file_pkg_proto_dialog_v1_dialog_proto_rawDesc)))
	})
	return file_pkg_proto_dialog_v1_dialog_proto_rawDescData
}

var file_pkg_proto_dialog_v1_dialog_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_proto_dialog_v1_dialog_proto_goTypes = []any{
	(*SendMessageRequest)(nil),    // 0: dialog.v1.SendMessageRequest
	(*SendMessageResponse)(nil),   // 1: dialog.v1.SendMessageResponse
	(*GetMessagesRequest)(nil),    // 2: dialog.v1.GetMessagesRequest
	(*DialogMessage)(nil),         // 3: dialog.v1.DialogMessage
	(*GetMessagesResponse)(nil),   // 4: dialog.v1.GetMessagesResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_pkg_proto_dialog_v1_dialog_proto_depIdxs = []int32{
	5, // 0: dialog.v1.SendMessageResponse.sent_at:type_name -> google.protobuf.Timestamp
	5, // 1: dialog.v1.DialogMessage.sent_at:type_name -> google.protobuf.Timestamp
	3, // 2: dialog.v1.GetMessagesResponse.messages:type_name -> dialog.v1.DialogMessage
	0, // 3: dialog.v1.DialogService.SendMessage:input_type -> dialog.v1.SendMessageRequest
	2, // 4: dialog.v1.DialogService.GetMessages:input_type -> dialog.v1.GetMessagesRequest
	1, // 5: dialog.v1.DialogService.SendMessage:output_type -> dialog.v1.SendMessageResponse
	4, // 6: dialog.v1.DialogService.GetMessages:output_type -> dialog.v1.GetMessagesResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_dialog_v1_dialog_proto_init() }
func file_pkg_proto_dialog_v1_dialog_proto_init() {
	if File_pkg_proto_dialog_v1_dialog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_dialog_v1_dialog_proto_rawDesc), len(file_pkg_proto_dialog_v1_dialog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_dialog_v1_dialog_proto_goTypes,
		DependencyIndexes: file_pkg_proto_dialog_v1_dialog_proto_depIdxs,
		MessageInfos:      file_pkg_proto_dialog_v1_dialog_proto_msgTypes,
	}.Build()
	File_pkg_proto_dialog_v1_dialog_proto = out.File
	file_pkg_proto_dialog_v1_dialog_proto_goTypes = nil
	file_pkg_proto_dialog_v1_dialog_proto_depIdxs = nil
}
