global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: 'app-metrics'
    static_configs:
      - targets: [ 'app:8080' ]  # Для доступа к локальному сервису
    metrics_path: '/metrics'

  - job_name: 'postgres-cluster'
    static_configs:
      - targets:
          - 'postgres-exporter-coord1:9187'
          - 'postgres-exporter-coord2:9187'
          - 'postgres-exporter-coord3:9187'
          - 'postgres-exporter-work1-1:9187'
          - 'postgres-exporter-work1-2:9187'
          - 'postgres-exporter-work2-1:9187'
          - 'postgres-exporter-work2-2:9187'
          # Если work3-* включены:
#          - 'postgres-exporter-work3-1:9187'
#          - 'postgres-exporter-work3-2:9187'
