global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgresql'
    static_configs:
      - targets:
          - 'postgres-exporter-1:9187'
          - 'postgres-exporter-2:9187'
          - 'postgres-exporter-3:9187'
    metrics_path: /metrics

  - job_name: 'node'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: 'app-metrics'
    static_configs:
      - targets: [ 'app:8080' ]  # Для доступа к локальному сервису
    metrics_path: '/metrics'
